Fix yaml oauth
FireTail-io/firetail-ruby-lib pull request #17
Opened 2024-04-26 13:43 UTC by muhammadn

## Describe your changes

1. Fixes the yaml parsing issue
2. Remove oauth from firetail logging since firetail endpoint does not accept oauth as schema.

## Issue ticket number and link

## Checklist before requesting a review

- [ ] I have resolved any merge conflicts
- [ ] I have run tests locally and they pass
- [ ] I have linted and auto-formatted the code
- [ ] If there is new or changed functionality, I have added/updated the tests
- [ ] If there is new or changed functionality, I have added/updated the documentation

2024-04-29 09:09 UTC, TheTeaCat requested changes

2024-04-29 09:09 UTC, TheTeaCat commented on lib/firetail.rb
> +      @url                = config['url'] ? config['url'] : "https://api.logging.eu-west-1.prod.firetail.app" # default goes to europe
```suggestion
      @url                = config['url'] ? config['url'] : "https://api.logging.eu-west-1.prod.firetail.app/logs/bulk" # default goes to europe
```

2024-04-29 09:09 UTC, TheTeaCat commented on examples/rails/config/firetail.yml
> +url: <%= ENV.fetch("FIRETAIL_URL") %>
```suggestion
url: <%= ENV.fetch("FIRETAIL_URL", nil) %>
```

2024-04-29 09:09 UTC, TheTeaCat commented on lib/generators/firetail/install/templates/firetail.yml
> +url: <%= ENV.fetch("FIRETAIL_URL") %>
```suggestion
url: <%= ENV.fetch("FIRETAIL_URL", nil) %>
```

2024-04-29 18:06 UTC, rileyfiretail submitted a review, later dismissed

2024-04-29 18:07 UTC, rileyfiretail submitted a review, later dismissed

2024-04-30 13:22 UTC, TheTeaCat approved these changes

2024-05-15 17:10 UTC, rileyfiretail approved these changes

2024-05-15 17:10 UTC, merged